/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}


declare module 'vue' {
  export interface GlobalComponents {
    Cartoon: typeof import('./../components/tabs/Cartoon.vue')['default']
    Chart: typeof import('./../components/Chart/index.vue')['default']
    GhostButton: typeof import('./../components/GhostButton.vue')['default']
    MovieItem: typeof import('./../components/common/MovieItem.vue')['default']
    Movies: typeof import('./../components/tabs/Movies.vue')['default']
    MovieTitle: typeof import('./../components/common/MovieTitle.vue')['default']
    MovieType1: typeof import('./../components/common/MovieType1.vue')['default']
    MovieType2: typeof import('./../components/common/MovieType2.vue')['default']
    NavBar: typeof import('./../components/NavBar.vue')['default']
    Recommend: typeof import('./../components/tabs/Recommend.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TabBar: typeof import('./../components/TabBar.vue')['default']
    Tv: typeof import('./../components/tabs/Tv.vue')['default']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanPopover: typeof import('vant/es')['Popover']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VarietyShow: typeof import('./../components/tabs/VarietyShow.vue')['default']
  }
}
